name: Excel Upload Workflow

on:
  push:
    # branches:
    #   - main
    paths:
      - 'files/*.xlsx'

permissions: 
  issues: write
  contents: read

env:
  TEMP_FOLDER_DATA: /tmp/xlsx2rss-data

jobs:
  main:
    runs-on: ubuntu-latest
    
    outputs:
      commit-files: ${{ steps.commit-file.outputs.files }}
      artifact-id: ${{ steps.artifact.outputs.artifact-id }}
      artifact-url: ${{ steps.artifact.outputs.artifact-url }}
      issue-number: ${{ steps.create-issue.outputs.issue-number }}
      issue-comment-body: ${{ steps.wait-issue.outputs.comment-body }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5.1.1
        with:
          python-version: '3.8'
          cache: 'pip'

      - name: Install Python Dependancies
        run: pip install -r requirements.txt

      # - name: Use Node.js
      #   uses: actions/setup-node@v4.0.3
      #   with:
      #     node-version: 16

      # - name: Cache node modules
      #   uses: actions/cache@v4.0.2
      #   id: cache
      #   with:
      #     path: node_modules
      #     key: npm-packages-${{ hashFiles('./actions/package-lock.json') }}

      # - name: Install Node Dependencies
      #   if: steps.cache.outputs.cache-hit != 'true'
      #   run: |
      #     cat ./actions/package.json > package.json
      #     cat ./actions/package-lock.json > package-lock.json
      #     npm ci

      - name: Get Commit File
        id: commit-file
        uses: ./actions/get-commit-file
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file-name: '*.xlsx'

      - name: Make temp folder
        run: mkdir ${{ env.TEMP_FOLDER_DATA }}

      - name: Run make_data code
        env:
          PASS_KEY: "${{ secrets.PASS_KEY }}"
          FILE_NAME: "${{ fromJson(steps.commit-file.outputs.files)[0].origin_name }}"
          TEMP_FOLDER_DATA: "${{ env.TEMP_FOLDER_DATA }}"
        run: |
          python make_data.py
          
      - name: Upload artifact
        id: artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: xlsx2rss-data
          path: ${{ env.TEMP_FOLDER_DATA }}

      - name: Create approval markdown
        env:
          FILE_ORIGIN_NAME: ${{ fromJson(steps.commit-file.outputs.files)[0].name }}
          UPLOAD_FILE_NAME: ${{ fromJson(steps.commit-file.outputs.files)[0].origin_name }}
          UPLOAD_FILE_URL: ${{ fromJson(steps.commit-file.outputs.files)[0].url.blob }}
          ARTIFACT_URL: ${{ steps.artifact.outputs.artifact-url }}
          TEMP_FOLDER_DATA: ${{ env.TEMP_FOLDER_DATA }}
        run: |
          python create_template.py

      - name: Create approval issue
        id: create-issue
        uses: ./actions/create-issue
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-title: "[Github Action] 파일 승인 요청"
          issue-body-url: ./templates/request_approve.tmp.md
          label: 승인요청

      - name: Alert ISSUE
        run: |
          echo "------------------------------------------------------------------------"
          echo "|"
          echo "| 이슈 생성: ${{ steps.create-issue.outputs.issue-url }}"
          echo "|"
          echo "------------------------------------------------------------------------"
          echo -e "\n\nWaiting..."

      - name: Wait for issue closed
        id: wait-issue
        uses: ./actions/wait-for-issue
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ steps.create-issue.outputs.issue-number }}
          interval-wait-time: 3000
          max-try: 600

  approved:
    needs: main
    runs-on: ubuntu-latest
    continue-on-error: false
    if: contains(fromJson('["O", "o", "ok", "OK", "Ok", "oK"]'), needs.main.outputs.issue-comment-body)
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Use Node.js
      #   uses: actions/setup-node@v4.0.3
      #   with:
      #     node-version: 16

      # - name: Cache node modules
      #   uses: actions/cache@v4.0.2
      #   id: cache
      #   with:
      #     path: node_modules
      #     key: npm-packages-${{ hashFiles('./actions/package-lock.json') }}

      # - name: Install Node Dependencies
      #   if: steps.cache.outputs.cache-hit != 'true'
      #   run: |
      #     cat ./actions/package.json > package.json
      #     cat ./actions/package-lock.json > package-lock.json
      #     npm ci

      - name: Use apt package cache
        uses: actions/cache@v4.0.2
        env:
          cache-name: cache-apt-packages
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-apt-${{ env.cache-name }}-${{ hashFiles('./apt-install-ver') }}
          
      - name: Download artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: xlsx2rss-data
          path: ${{ env.TEMP_FOLDER_DATA }}

      - name: Add issue comment
        uses: ./actions/add-issue-comment
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment: "승인되었습니다"
          issue-number: ${{ needs.main.outputs.issue-number }}
          # state: closed
          # state-reason: completed

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Upload Server
        uses: ./actions/send-lohas-req
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-id: ${{ needs.main.outputs.artifact-id }}
          jwt-secret: ${{ secrets.JWT_SECRET }}
          issue-number: ${{ needs.main.outputs.issue-number }}
          api-url: ${{ secrets.API_URL }}


      # - name: Upload server
      #   env:
      #     API_URL: ${{ secrets.API_URL }}
      #     JWT_SECRET: ${{ secrets.JWT_SECRET }}
      #   run: |
      #     timestamp=$(date +%s)
      #     header=$(echo -n '{"alg":"HS256","typ":"JWT"}' | base64 | tr -d '=' | tr '/+' '_-')
      #     payload=$(jq -n \
      #       --arg sha "${{ github.sha }}" \
      #       --arg repo "${{ github.repository }}" \
      #       --arg time $timestamp \
      #       --arg iat $timestamp \
      #       --arg exp $((timestamp + 300)) \
      #       '{"sha":$sha,"repository":$repo,"timestamp":$time,"iat":($iat|tonumber),"exp":($exp|tonumber)}' | base64 | tr -d '=' | tr '/+' '_-')
      #     signature=$(echo -n "${header}.${payload}" | openssl dgst -binary -sha256 -hmac "${JWT_SECRET}" | base64 | tr -d '=' | tr '/+' '_-')
      #     jwt="${header}.${payload}.${signature}"
      #     echo "::add-mask::$jwt"
      #     echo "::add-mask::$header"
      #     echo "::add-mask::$payload"
      #     echo "::add-mask::$signature"

      #     curl -X POST $API_URL \
      #       -H "Content-Type: application/json" \
      #       -H "Authorization: Bearer $jwt" \
      #       -d "$(jq -n \
      #         --arg repo "${{ github.repository }}" \
      #         --arg artifact_id "${{ needs.main.outputs.artifact-id }}" \
      #         --arg artifact_url "${{ needs.main.outputs.artifact-url }}" \
      #         --arg issue_num "${{ needs.main.outputs.issue-number }}" \
      #         '{"repository":$repo,"artifact_id":$artifact_id,"artifact_url":$artifact_url,"issue_num":$issue_num}')"

  denied:
    needs: main
    runs-on: ubuntu-latest
    continue-on-error: true
    if: ${{ ! contains(fromJson('["O", "o", "ok", "OK", "Ok", "oK"]'), needs.main.outputs.issue-comment-body) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Use Node.js
      #   uses: actions/setup-node@v4.0.3
      #   with:
      #     node-version: 16

      # - name: Cache node modules
      #   uses: actions/cache@v4.0.2
      #   id: cache
      #   with:
      #     path: node_modules
      #     key: npm-packages-${{ hashFiles('./actions/package-lock.json') }}

      # - name: Install Node Dependencies
      #   if: steps.cache.outputs.cache-hit != 'true'
      #   run: |
      #     cat ./actions/package.json > package.json
      #     cat ./actions/package-lock.json > package-lock.json
      #     npm ci
          
      - name: Add issue comment
        uses: ./actions/add-issue-comment
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment: "승인 거부되었습니다"
          issue-number: ${{ needs.main.outputs.issue-number }}
          state: closed
          state-reason: not_planned